version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-container
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Purolator@2024"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
